version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - api-gateway
  service-auth:
    build: ./backend/service-auth
    ports:
      - "4001:4001"
    environment:
      - NODE_ENV=development
    volumes:
      - ./shared:/app/shared
  service-chat:
    build: ./backend/service-chat
    ports:
      - "4002:4002"
    environment:
      - NODE_ENV=development
    volumes:
      - ./shared:/app/shared

  service-game:
    build: ./backend/service-game
    ports:
      - "4003:4003"
    environment:
      - NODE_ENV=development
    volumes:
      - ./shared:/app/shared

  service-user:
    build: ./backend/service-user
    ports:
      - "4004:4004"
    environment:
      - NODE_ENV=development
    volumes:
      - ./shared:/app/shared

  api-gateway:
    build: ./backend/api-gateway
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    volumes:
      - ./shared:/app/shared
    depends_on:
      - service-auth
      - service-user
      - service-chat
      - service-game
